apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-mae-consumer
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-mae-consumer
  template:
    metadata:
      labels:
        app: datahub-mae-consumer
    spec:
      containers:
        - name: datahub-mae-consumer
          image: acryldata/datahub-mae-consumer:latest
          envFrom:
            - configMapRef:
                name: datahub-mae-consumer-config
          resources: {}
            # limits:
            #   memory: "1Gi"
            #   cpu: "500m"
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"