apiVersion: v1
kind: ConfigMap
metadata:
  name: datahub-mce-consumer-config
  namespace: datahub
data:
  DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID: "generic-duhe-consumer-job-client-mcp"
  MCE_CONSUMER_ENABLED: "true"
  EBEAN_DATASOURCE_USERNAME: "datahub"
  EBEAN_DATASOURCE_PASSWORD: "datahub"
  EBEAN_DATASOURCE_HOST: "mysql:3306"
  EBEAN_DATASOURCE_URL: "jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8"
  EBEAN_DATASOURCE_DRIVER: "com.mysql.jdbc.Driver"
  KAFKA_BOOTSTRAP_SERVER: "kafka-0.kafka.datahub.svc.cluster.local:29092"
  KAFKA_SCHEMAREGISTRY_URL: "http://schema-registry.schema-registry.datahub.svc.cluster.local:8081"
  ELASTICSEARCH_HOST: "elasticsearch-0.elasticsearch.datahub.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200"
  ES_BULK_REFRESH_POLICY: "WAIT_UNTIL"
  GRAPH_SERVICE_DIFF_MODE_ENABLED: "true"
  GRAPH_SERVICE_IMPL: "elasticsearch"
  JAVA_OPTS: "-Xms1g -Xmx1g"
  ENTITY_REGISTRY_CONFIG_PATH: "/datahub/datahub-mce-consumer/resources/entity-registry.yml"
  DATAHUB_SYSTEM_CLIENT_ID: "__datahub_system"
  DATAHUB_SYSTEM_CLIENT_SECRET: "JohnSnowKnowsNothing"
  DATAHUB_SERVER_TYPE: "quickstart"
  DATAHUB_TELEMETRY_ENABLED: "true"
  ENTITY_SERVICE_ENABLE_RETENTION: "true"
  MAE_CONSUMER_ENABLED: "false"
  PE_CONSUMER_ENABLED: "false"
  UI_INGESTION_ENABLED: "false"