apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-upgrade
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-upgrade
  template:
    metadata:
      labels:
        app: datahub-upgrade
    spec:
      containers:
        - name: datahub-upgrade
          image: acryldata/datahub-upgrade:latest
          command:
            - "-u"
            - "SystemUpdate"
          envFrom:
            - configMapRef:
                name: datahub-upgrade-config
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
