apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-frontend
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-frontend
  template:
    metadata:
      labels:
        app: datahub-frontend
    spec:
      containers:
        - name: datahub-frontend
          image: acryldata/datahub-frontend-react:latest
          ports:
            - containerPort: 9002
          envFrom:
            - configMapRef:
                name: datahub-frontend-config
          resources: {}
            # limits:
            #   memory: "1Gi"
            #   cpu: "500m"
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"
          readinessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 10          
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-frontend
  namespace: datahub
spec:
  selector:
    app: datahub-frontend
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002