apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-mce-consumer
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-mce-consumer
  template:
    metadata:
      labels:
        app: datahub-mce-consumer
    spec:
      containers:
        - name: datahub-mce-consumer
          image: acryldata/datahub-mce-consumer:latest
          envFrom:
            - configMapRef:
                name: datahub-mce-consumer-config
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"