---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-gms
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-gms
  template:
    metadata:
      labels:
        app: datahub-gms
    spec:
      containers:
        - name: datahub-gms
          image: acryldata/datahub-gms:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: datahub-gms-config
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - "curl"
                - "-sS"
                - "--fail"
                - "http://datahub-gms:8080/health"
            initialDelaySeconds: 90
            periodSeconds: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "curl"
                - "-sS"
                - "--fail"
                - "http://datahub-gms:8080/health"
            initialDelaySeconds: 90
            periodSeconds: 1
            failureThreshold: 3
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-gms
  namespace: datahub
spec:
  selector:
    app: datahub-gms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080