---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: datahub-es-cluster
    network.host: 0.0.0.0
    node.roles: [ "master", "data", "ingest" ]
    bootstrap.memory_lock: true
    path.data: /usr/share/elasticsearch/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: logging
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        stack: logging
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          value: -Xms128m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
        - name: ES_HEAP_SIZE
          value: "512m"
        - name: discovery.seed_hosts
          value: "elasticsearch-0.elasticsearch.default.svc.cluster.local,elasticsearch-1.elasticsearch.default.svc.cluster.local,elasticsearch-2.elasticsearch.default.svc.cluster.local"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
        - name: node.max_local_storage_nodes
          value: "3"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: xpack.security.enabled
          value: "false" 
        - name: cluster.name
          value: "datahub-es-cluster"            
        ports:
        - containerPort: 9200
          name: external
        - containerPort: 9300
          name: internal
        resources:
          limits:
            memory: 512m
            cpu: 0.5
          requests:
            memory: 128m
            cpu: 0.1
        volumeMounts:
        - name: config
          mountPath: /etc/elasticsearch/elasticsearch.yml
          subPath: elasticsearch.yml
#        - name: elasticsearch-data
#          mountPath: /usr/share/elasticsearch/data
      securityContext:
        fsGroup: 1000
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
#      - name: elasticsearch-data
#        persistentVolumeClaim:
#          claimName: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: external
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: internal
      protocol: TCP
      port: 9300
      targetPort: 9300
