---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: logging
data:
  elasticsearch.yml: |
    cluster.name: datahub-es-cluster
    node.name: node-1
    path.data: /usr/share/elasticsearch/data
    http:
      host: 0.0.0.0
      port: 9200
    bootstrap.memory_lock: true
    transport.host: 127.0.0.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: logging
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        stack: logging
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
        - name: discovery.type
          value: single-node
        - name: discovery.seed_hosts
          value: "elasticsearch.elasticsearch.default.svc.cluster.local:9200"
        - name: node.max_local_storage_nodes
          value: "1" 
        - name: xpack.security.enabled
          value: "false" 
        - name: cluster.name
          value: "datahub-es-cluster"            
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          limits:
            memory: "2147483648"
        volumeMounts:
        - name: config
          mountPath: /etc/elasticsearch/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      securityContext:
        fsGroup: 1000
      volumes:
      - name: config
        configMap:
          name: elasticsearch
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: external
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: internal
      protocol: TCP
      port: 9300
      targetPort: 9300
        
