apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-setup-config
  namespace: datahub
data:
  ELASTICSEARCH_HOST: "elasticsearch-0.elasticsearch.datahub.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_PROTOCOL: "http"
  ELASTICSEARCH_USE_SSL: "false"
