apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datahub-mae-consumer
  name: datahub-mae-consumer
  namespace: datahub
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datahub-mae-consumer
  strategy:
    #rollingUpdate:
    #  maxSurge: 25%
    #  maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/kafka-network: "true"
        app: datahub-mae-consumer
    spec:
      containers:
      - env:
        - name: DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID
          value: datahub-duhe-consumer-job-client-gms
        - name: MCE_CONSUMER_ENABLED
          value: "true"
        - name: MAE_CONSUMER_ENABLED
          value: "true"
        - name: ENTITY_REGISTRY_CONFIG_PATH
          value: /datahub/datahub-gms/resources/entity-registry.yml
        - name: EBEAN_DATASOURCE_USERNAME
          value: postgres
        - name: EBEAN_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        - name: EBEAN_DATASOURCE_HOST
          value: postgres-0.postgres.datahub.svc.cluster.local:5432
        - name: EBEAN_DATASOURCE_URL
          value: jdbc:postgresql://postgres.datahub.svc.cluster.local:5432/datahub
        - name: EBEAN_DATASOURCE_DRIVER
          value: org.postgresql.Driver
        - name: KAFKA_BOOTSTRAP_SERVER
          value: kafka-0.kafka.datahub.svc.cluster.local:29092
        - name: KAFKA_SCHEMAREGISTRY_URL
          value: http://schema-registry-0.schema-registry.datahub.svc.cluster.local:8080/schema-registry/api/
        - name: SCHEMA_REGISTRY_TYPE
          value: INTERNAL
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-0.easticsearch.datahub.svc.cluster.local
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: SKIP_ELASTICSEARCH_CHECK
          value: "false"
        - name: ELASTICSEARCH_USE_SSL
          value: "false"
        - name: GRAPH_SERVICE_IMPL
          value: elasticsearch
        - name: ENTITY_SERVICE_ENABLE_RETENTION
          value: "true"
        - name: ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX
          value: "true"
        - name: ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX
          value: "true"
        - name: GRAPH_SERVICE_DIFF_MODE_ENABLED
          value: "true"
        - name: GRAPHQL_QUERY_INTROSPECTION_ENABLED
          value: "true"
        - name: UI_INGESTION_ENABLED
          value: "true"
        - name: PE_CONSUMER_ENABLED
          value: "true"
        image: docker.io/acryldata/datahub-gms:v0.15.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: datahub-gms
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 4318
          name: jmx
          protocol: TCP
        readinessProbe:
          failureThreshold: 8
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        #resources:
        #  limits:
        #    memory: 2Gi
        #  requests:
        #    cpu: 100m
        #    memory: 1Gi
        securityContext: {}
      restartPolicy: Always
      securityContext: {}
      #serviceAccount: datahub-datahub-gms
