apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: datahub-elasticsearch-setup-job
  name: datahub-elasticsearch-setup-job
  namespace: datahub
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      app: datahub-elasticsearch-setup-job
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datahub-elasticsearch-setup-job
        job-name: datahub-elasticsearch-setup-job
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-master
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: SKIP_ELASTICSEARCH_CHECK
          value: "false"
        - name: ELASTICSEARCH_INSECURE
          value: "false"
        - name: ELASTICSEARCH_USE_SSL
          value: "false"
        - name: DATAHUB_ANALYTICS_ENABLED
          value: "true"
        image: docker.io/acryldata/datahub-elasticsearch-setup:v0.14.1
        imagePullPolicy: IfNotPresent
        name: datahub-elasticsearch-setup-job
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 512Mi
        #  requests:
        #    cpu: 300m
        #    memory: 256Mi
        securityContext:
          runAsUser: 1000
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
