apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: datahub-system-update-job
  name: datahub-system-update-job
  namespace: datahub
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      app: datahub-system-update-job
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datahub-system-update-job
        job-name: datahub-system-update-job
    spec:
      containers:
      - args:
        - -u
        - SystemUpdateBlocking
        env:
        - name: ENTITY_REGISTRY_CONFIG_PATH
          value: /datahub/datahub-gms/resources/entity-registry.yml
        - name: DATAHUB_GMS_HOST
          value: datahub-gms.datahub.svc.cluster.local
        - name: DATAHUB_GMS_PORT
          value: "8080"
        - name: DATAHUB_MAE_CONSUMER_HOST
          value: datahub-mae-consumer
        - name: DATAHUB_MAE_CONSUMER_PORT
          value: "9091"
        - name: EBEAN_DATASOURCE_USERNAME
          value: postgres
        - name: EBEAN_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        - name: EBEAN_DATASOURCE_HOST
          value: postgres-0.postgres.datahub.svc.cluster.local:5432
        - name: EBEAN_DATASOURCE_URL
          value: jdbc:postgresql://postgres-0.postgres.datahub.svc.cluster.local:5432/datahub
        - name: EBEAN_DATASOURCE_DRIVER
          value: org.postgresql.Driver
        - name: KAFKA_BOOTSTRAP_SERVER
          value: prerequisites-kafka:9092
        - name: KAFKA_SCHEMAREGISTRY_URL
          value: http://datahub-gms.datahub.svc.cluster.local:8080/schema-registry/api/
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-0.easticsearch.datahub.svc.cluster.local
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: GRAPH_SERVICE_IMPL
          value: elasticsearch
        - name: DATAHUB_ANALYTICS_ENABLED
          value: "true"
        - name: SCHEMA_REGISTRY_SYSTEM_UPDATE
          value: "true"
        - name: SPRING_KAFKA_PROPERTIES_AUTO_REGISTER_SCHEMAS
          value: "true"
        - name: SPRING_KAFKA_PROPERTIES_USE_LATEST_VERSION
          value: "true"
        - name: SCHEMA_REGISTRY_TYPE
          value: INTERNAL
        - name: ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES
          value: "true"
        - name: ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX
          value: "true"
        - name: ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX
          value: "true"
        image: docker.io/acryldata/datahub-upgrade:v0.15.0.1
        imagePullPolicy: IfNotPresent
        name: datahub-system-update-job
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 2Gi
        #  requests:
        #    cpu: 300m
        #    memory: 2Gi
        securityContext: {}
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
