apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: datahub-mysql-setup-job
  name: datahub-mysql-setup-job
  namespace: datahub
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      app: datahub-mysql-setup-job
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datahub-mysql-setup-job
        job-name: datahub-mysql-setup-job
    spec:
      containers:
      - env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql-secrets
        - name: MYSQL_HOST
          value: prerequisites-mysql
        - name: MYSQL_PORT
          value: "3306"
        image: docker.io/acryldata/datahub-mysql-setup:v0.14.1
        imagePullPolicy: IfNotPresent
        name: datahub-mysql-setup-job
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 512Mi
        #  requests:
        #    cpu: 300m
        #    memory: 256Mi
        securityContext:
          runAsUser: 1000
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
