apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datahub-frontend
  name: datahub-frontend
  namespace: datahub
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datahub-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datahub-frontend
    spec:
      containers:
      - env:
        - name: DATAHUB_GMS_HOST
          value: datahub-gms.datahub.svc.cluster.local
        - name: DATAHUB_GMS_PORT
          value: "8080"
        - name: DATAHUB_SECRET
          value: datahub
          #valueFrom:
          #  secretKeyRef:
          #    key: datahub.gms.secret
          #    name: datahub-gms-secret
        - name: DATAHUB_PLAY_MEM_BUFFER_SIZE
          value: 10MB
        - name: DATAHUB_ANALYTICS_ENABLED
          value: "true"
        - name: KAFKA_BOOTSTRAP_SERVER
          value: kafka-0.kafka.datahub.svc.cluster.local:9092
        - name: ENFORCE_VALID_EMAIL
          value: "true"
        - name: ELASTIC_CLIENT_HOST
          value: elasticsearch-0.easticsearch.datahub.svc.cluster.local
        - name: ELASTIC_CLIENT_PORT
          value: "9200"
        - name: ELASTIC_CLIENT_USE_SSL
          value: "false"
        - name: METADATA_SERVICE_AUTH_ENABLED
          value: "true"
        image: docker.io/acryldata/datahub-frontend-react:v0.15.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /admin
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: datahub-frontend
        ports:
        - containerPort: 9002
          name: http
          protocol: TCP
        - containerPort: 4318
          name: jmx
          protocol: TCP
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /admin
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        #resources:
        #  limits:
        #    memory: 1400Mi
        #  requests:
        #    cpu: 100m
        #    memory: 512Mi
        securityContext: {}
      restartPolicy: Always
      securityContext: {}
      #serviceAccount: datahub-datahub-frontend
      terminationGracePeriodSeconds: 150
