apiVersion: v1
kind: Service
metadata:
  labels:
    service: datahub-frontend
  name: datahub-frontend
  namespace: datahub
spec:
  ports:
  - name: http
    nodePort: 30890
    port: 9002
    protocol: TCP
    targetPort: http
  - name: jmx
    nodePort: 32246
    port: 4318
    protocol: TCP
    targetPort: jmx
  selector:
    app: datahub-frontend
  sessionAffinity: None
  type: LoadBalancer
