apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: datahub-kafka-setup-job
  name: datahub-kafka-setup-job
  namespace: datahub
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      app: datahub-kafka-setup-job
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datahub-kafka-setup-job
        job-name: datahub-kafka-setup-job
    spec:
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: prerequisites-zookeeper:2181
        - name: KAFKA_BOOTSTRAP_SERVER
          value: kafka-0.kafka.datahub.svc.cluster.local:9092
        - name: MAX_MESSAGE_BYTES
          value: "5242880"
        - name: USE_CONFLUENT_SCHEMA_REGISTRY
          value: "false"
        image: docker.io/acryldata/datahub-kafka-setup:v0.15.0.1
        imagePullPolicy: IfNotPresent
        name: datahub-kafka-setup-job
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 1Gi
        #  requests:
        #    cpu: 300m
        #    memory: 768Mi
        securityContext:
          runAsUser: 1000
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
