apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-2"
  creationTimestamp: "2025-02-09T11:06:56Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datahub
    app.kubernetes.io/version: 0.14.1
    helm.sh/chart: datahub-0.4.27
  name: datahub-nocode-migration-job
  namespace: datahub
  resourceVersion: "449442"
  uid: b0a5833f-df35-4e5d-98f5-166be1cbc594
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: b0a5833f-df35-4e5d-98f5-166be1cbc594
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: b0a5833f-df35-4e5d-98f5-166be1cbc594
        batch.kubernetes.io/job-name: datahub-nocode-migration-job
        controller-uid: b0a5833f-df35-4e5d-98f5-166be1cbc594
        job-name: datahub-nocode-migration-job
    spec:
      containers:
      - args:
        - -u
        - NoCodeDataMigration
        - -a
        - batchSize=1000
        - -a
        - batchDelayMs=100
        - -a
        - dbType=MYSQL
        env:
        - name: ENTITY_REGISTRY_CONFIG_PATH
          value: /datahub/datahub-gms/resources/entity-registry.yml
        - name: DATAHUB_GMS_HOST
          value: datahub-datahub-gms
        - name: DATAHUB_GMS_PORT
          value: "8080"
        - name: DATAHUB_MAE_CONSUMER_HOST
          value: datahub-datahub-mae-consumer
        - name: DATAHUB_MAE_CONSUMER_PORT
          value: "9091"
        - name: EBEAN_DATASOURCE_USERNAME
          value: root
        - name: EBEAN_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql-secrets
        - name: EBEAN_DATASOURCE_HOST
          value: prerequisites-mysql:3306
        - name: EBEAN_DATASOURCE_URL
          value: jdbc:mysql://prerequisites-mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
        - name: EBEAN_DATASOURCE_DRIVER
          value: com.mysql.cj.jdbc.Driver
        - name: KAFKA_BOOTSTRAP_SERVER
          value: prerequisites-kafka:9092
        - name: KAFKA_PRODUCER_COMPRESSION_TYPE
          value: none
        - name: KAFKA_PRODUCER_MAX_REQUEST_SIZE
          value: "5242880"
        - name: KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES
          value: "5242880"
        - name: KAFKA_SCHEMAREGISTRY_URL
          value: http://datahub-datahub-gms:8080/schema-registry/api/
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-master
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: SKIP_ELASTICSEARCH_CHECK
          value: "false"
        - name: ELASTICSEARCH_INSECURE
          value: "false"
        - name: ELASTICSEARCH_USE_SSL
          value: "false"
        - name: GRAPH_SERVICE_IMPL
          value: elasticsearch
        - name: METADATA_CHANGE_EVENT_NAME
          value: MetadataChangeEvent_v4
        - name: FAILED_METADATA_CHANGE_EVENT_NAME
          value: FailedMetadataChangeEvent_v4
        - name: METADATA_AUDIT_EVENT_NAME
          value: MetadataAuditEvent_v4
        - name: METADATA_CHANGE_PROPOSAL_TOPIC_NAME
          value: MetadataChangeProposal_v1
        - name: FAILED_METADATA_CHANGE_PROPOSAL_TOPIC_NAME
          value: FailedMetadataChangeProposal_v1
        - name: METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME
          value: MetadataChangeLog_Versioned_v1
        - name: METADATA_CHANGE_LOG_TIMESERIES_TOPIC_NAME
          value: MetadataChangeLog_Timeseries_v1
        - name: DATAHUB_UPGRADE_HISTORY_TOPIC_NAME
          value: DataHubUpgradeHistory_v1
        - name: DATAHUB_SYSTEM_CLIENT_ID
          value: __datahub_system
        - name: DATAHUB_SYSTEM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: system_client_secret
              name: datahub-auth-secrets
        image: docker.io/acryldata/datahub-upgrade:v0.14.1
        imagePullPolicy: IfNotPresent
        name: datahub-upgrade-job
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  active: 1
  ready: 0
  startTime: "2025-02-09T11:06:56Z"
  uncountedTerminatedPods: {}
