apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: datahub
    meta.helm.sh/release-namespace: datahub
  creationTimestamp: "2025-02-10T04:53:26Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: acryl-datahub-actions
    app.kubernetes.io/version: 0.1.1
    helm.sh/chart: acryl-datahub-actions-0.2.148
  name: datahub-acryl-datahub-actions
  namespace: datahub
  resourceVersion: "470164"
  uid: b5f626c5-3bdd-4b97-881c-546d490821dc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: datahub
      app.kubernetes.io/name: acryl-datahub-actions
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: datahub
        app.kubernetes.io/name: acryl-datahub-actions
    spec:
      containers:
      - env:
        - name: DATAHUB_GMS_PROTOCOL
          value: http
        - name: DATAHUB_GMS_HOST
          value: datahub-datahub-gms
        - name: DATAHUB_GMS_PORT
          value: "8080"
        - name: GMS_HOST
          value: datahub-datahub-gms
        - name: GMS_PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVER
          value: prerequisites-kafka:9092
        - name: SCHEMA_REGISTRY_URL
          value: http://datahub-datahub-gms:8080/schema-registry/api/
        - name: KAFKA_AUTO_OFFSET_POLICY
          value: latest
        - name: METADATA_CHANGE_EVENT_NAME
          value: MetadataChangeEvent_v4
        - name: FAILED_METADATA_CHANGE_EVENT_NAME
          value: FailedMetadataChangeEvent_v4
        - name: METADATA_AUDIT_EVENT_NAME
          value: MetadataAuditEvent_v4
        - name: DATAHUB_USAGE_EVENT_NAME
          value: DataHubUsageEvent_v1
        - name: METADATA_CHANGE_PROPOSAL_TOPIC_NAME
          value: MetadataChangeProposal_v1
        - name: FAILED_METADATA_CHANGE_PROPOSAL_TOPIC_NAME
          value: FailedMetadataChangeProposal_v1
        - name: METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME
          value: MetadataChangeLog_Versioned_v1
        - name: METADATA_CHANGE_LOG_TIMESERIES_TOPIC_NAME
          value: MetadataChangeLog_Timeseries_v1
        - name: PLATFORM_EVENT_TOPIC_NAME
          value: PlatformEvent_v1
        - name: DATAHUB_SYSTEM_CLIENT_ID
          value: __datahub_system
        - name: DATAHUB_SYSTEM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: system_client_secret
              name: datahub-auth-secrets
        image: docker.io/acryldata/datahub-actions:v0.1.1
        imagePullPolicy: IfNotPresent
        name: acryl-datahub-actions
        ports:
        - containerPort: 9093
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 150
status:
  conditions:
  - lastTransitionTime: "2025-02-10T04:53:26Z"
    lastUpdateTime: "2025-02-10T04:53:26Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-02-10T04:53:26Z"
    lastUpdateTime: "2025-02-10T04:53:27Z"
    message: ReplicaSet "datahub-acryl-datahub-actions-5d665698f4" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
