apiVersion: v1
kind: Service
metadata:
  labels:
    service: datahub-gms
  name: datahub-gms
  namespace: datahub
spec:
  ports:
  - name: http
    nodePort: 30440
    port: 8080
    protocol: TCP
    targetPort: http
  - name: jmx
    nodePort: 31402
    port: 4318
    protocol: TCP
    targetPort: jmx
  selector:
    app: datahub-gms
  sessionAffinity: None
  type: LoadBalancer
