apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
  creationTimestamp: "2025-02-09T11:04:00Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datahub
    app.kubernetes.io/version: 0.14.1
    helm.sh/chart: datahub-0.4.27
  name: datahub-mysql-setup-job
  namespace: datahub
  resourceVersion: "448937"
  uid: b88be90c-6479-482f-8f6f-16a06409af52
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: b88be90c-6479-482f-8f6f-16a06409af52
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: b88be90c-6479-482f-8f6f-16a06409af52
        batch.kubernetes.io/job-name: datahub-mysql-setup-job
        controller-uid: b88be90c-6479-482f-8f6f-16a06409af52
        job-name: datahub-mysql-setup-job
    spec:
      containers:
      - env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql-secrets
        - name: MYSQL_HOST
          value: prerequisites-mysql
        - name: MYSQL_PORT
          value: "3306"
        image: docker.io/acryldata/datahub-mysql-setup:v0.14.1
        imagePullPolicy: IfNotPresent
        name: mysql-setup-job
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
status:
  active: 1
  ready: 0
  startTime: "2025-02-09T11:04:00Z"
  uncountedTerminatedPods: {}
