apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: datahub
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.2
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpwd
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "datahub"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "false"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-db
  volumeClaimTemplates:
  - metadata:
      name: mysql-db
    spec:
      storageClassName: sc-local
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: datahub
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
  clusterIP: "None"
