apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.8.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: "500m"
              memory: 200Mi
          ports:
            - containerPort: 8081
            - containerPort: 30092
          env:
            - name: PORT
              value: "8081"
            - name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
              value: "DEBUG"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "PLAINTEXT://0.0.0.0:8081,PLAINTEXT://0.0.0.0:30092"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry.datahub.svc.cluster.local"
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: "zookeeper.datahub.svc.cluster.local:2181"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://kafka.datahub.svc.cluster.local:9092"
            - name: SCHEMA_REGISTRY_DEBUG
              value: 'true'
          livenessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: datahub
spec:
  selector:
    app: schema-registry
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: external
      protocol: TCP
      port: 30092
      targetPort: 30092
