apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: datahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.4.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: "500m"
              memory: 200Mi
          ports:
            - containerPort: 8081
            - containerPort: 30092
          # envFrom:
          #   - configMapRef:
          #       name: schema-registry-config
          env:
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081,http://0.0.0.0:30092"
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: "zookeeper-0.zookeeper.datahub.svc.cluster.local:2181"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://kafka-0.kafka.datahub.svc.cluster.local:9092"
            - name: SCHEMA_REGISTRY_DEBUG
              value: 'true'
          livenessProbe:
            exec:
              command:
                - "nc"
                - "-z"
                - "schema-registry"
                - "8081"
            initialDelaySeconds: 60
            periodSeconds: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "nc"
                - "-z"
                - "schema-registry"
                - "8081"
            initialDelaySeconds: 60
            periodSeconds: 1
            failureThreshold: 3
            timeoutSeconds: 5            
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: datahub
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: external
      protocol: TCP
      port: 30092
      targetPort: 30092                