apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
  namespace: datahub
data:
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka-0.kafka.datahub.svc.cluster.local:29092"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081,http://0.0.0.0:30092"
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"
