apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
  namespace: datahub
data:
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081,http://0.0.0.0:30092"
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"
  SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper-0.zookeeper.datahub.svc.cluster.local:2181"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-0.kafka.datahub.svc.cluster.local:9092"
  SCHEMA_REGISTRY_DEBUG: 'true'
